id = "lua"
name = "Lua"
description = "Lua support."
version = "0.1.5"
schema_version = 1
authors = ["Max Brunsfeld <max@zed.dev>"]
repository = "https://github.com/zed-extensions/lua"

[language_servers.lua-language-server]
name = "LuaLS"
language = "Lua"

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "4569d1c361129e71a205b94a05e158bd71b1709f"
