id = "lua"
name = "Lua"
description = "Lua support."
version = "0.1.6"
schema_version = 1
authors = ["Max Brunsfeld <max@zed.dev>"]
repository = "https://github.com/zed-extensions/lua"

[language_servers.lua-language-server]
name = "LuaLS"
languages = ["Lua", "EmmyLuadoc"]

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "d76023017f7485eae629cb60d406c7a1ca0f40c9"

[grammars.emmyluadoc]
repository = "https://github.com/EmmyLuaLs/tree-sitter-emmyluadoc"
commit = "ea755c0fd34c07e16597bd62a404d6eba2a3891e"
